version: '3.7'

services:

  web:
    container_name: ideabox_front
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true